# Node.js CI/CD with local Docker deployment
name: Local Docker CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    env:
      PORT: ${{ secrets.PORT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image locally
        run: docker build -t ugurdindar.com:latest .

      - name: Stop and remove old container
        run: |
          docker stop ugurdindar.com || true
          docker rm ugurdindar.com || true

      - name: Run new container
        run: docker run -d --name ugurdindar.com -p $PORT:$PORT -e PORT=$PORT --restart unless-stopped ugurdindar.com:latest
